twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'form/json_key_value.html.twig'
        - 'form/single_file_picker.html.twig'

when@test:
    twig:
        strict_variables: true
